include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  # reset board configuration
  - board: seeeduino_xiao_ble
    shield: settings_reset
